---
- name: Delete VM and associated storage disks
  hosts: all

  tasks:
    - name: Shutdown VM
      command: /usr/bin/virsh destroy '{{ survey_del_hostname }}'

    - name: Delete VM and attached storage from LibVirt
      command: virsh undefine '{{ survey_del_hostname }}' --remove-all-storage
